emailSendSuccess() ::= <<

<div class="wrapper">
    <div>
    <h2 style="text-align:center;padding-top:100px;">
    Success! Please close this window and refresh your email page if you are in the Sent Mail Page.(Sorry about that, we will improve it soon.)
    </h2>
    <div style="text-align:center;">
    <a href="/inbox">
    Or after reply/forward successful, click to return inbox page.
    </a>
    </div>
    </div>
    <div class="amail-footer-bar">
        <div class="footer content clearfix">
            <ul>
                <li>
                    <a href="/aboutAmail">
                        About Amail
                    </a>
                </li>
                <li>
                    <a href="/service">
                        Service
                    </a>
                </li>
                <li>
                    <a href="/help">
                        Help
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

>>